// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-J0W-2UhSE7cIzPsm9csVJEtXKniuI0',
    appId: '1:273939537978:web:ebe52119a8971eafdd1503',
    messagingSenderId: '273939537978',
    projectId: 'mcproject-a61dc',
    authDomain: 'mcproject-a61dc.firebaseapp.com',
    storageBucket: 'mcproject-a61dc.firebasestorage.app',
    measurementId: 'G-NE370B8NX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wkVU7DSDAllXCZ_RXaIywnIBZk0ubV0',
    appId: '1:273939537978:android:272ab9883f771c92dd1503',
    messagingSenderId: '273939537978',
    projectId: 'mcproject-a61dc',
    storageBucket: 'mcproject-a61dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ZO_jsGnn4jez6P63UFVKJelnvHcLjUs',
    appId: '1:273939537978:ios:fe3f869a45854c74dd1503',
    messagingSenderId: '273939537978',
    projectId: 'mcproject-a61dc',
    storageBucket: 'mcproject-a61dc.firebasestorage.app',
    iosBundleId: 'com.example.mcProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ZO_jsGnn4jez6P63UFVKJelnvHcLjUs',
    appId: '1:273939537978:ios:fe3f869a45854c74dd1503',
    messagingSenderId: '273939537978',
    projectId: 'mcproject-a61dc',
    storageBucket: 'mcproject-a61dc.firebasestorage.app',
    iosBundleId: 'com.example.mcProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB-J0W-2UhSE7cIzPsm9csVJEtXKniuI0',
    appId: '1:273939537978:web:4e7c5c28baf1a1cbdd1503',
    messagingSenderId: '273939537978',
    projectId: 'mcproject-a61dc',
    authDomain: 'mcproject-a61dc.firebaseapp.com',
    storageBucket: 'mcproject-a61dc.firebasestorage.app',
    measurementId: 'G-YM8577CDLX',
  );

}